# Generated by Django 4.1.1 on 2022-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_message_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ManyToManyField(blank=True, null=True, related_name='add_channel', to='app.channel'),
        ),
    ]
